use_frameworks!
pod 'Firebase', '>= 2.3.3'
pod 'JSQMessagesViewController'
pod 'Bond', '4.0.0-beta1'
pod 'SVPullToRefresh', :git => 'https://github.com/gabro/SVPullToRefresh.git', :branch => 'top-infinitescrolling'
pod 'SVProgressHUD'
