# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Genie' do
pod 'Firebase', '>= 2.3.3'
end

target 'GenieTests' do

end

target 'GenieUITests' do

end

